installation:
  controlPlaneReplicas: 1
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: Iptables
    nodeAddressAutodetectionV4:
      cidrs:
        - 192.168.57.0/24
    ipPools:
      - cidr: 172.20.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
apiServer:
  enabled: false
goldmane:
  enabled: false
whisker:
  enabled: false
